# Generated by Codex on 2026-04-21

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("jobs", "Category")
    for name in [
        "Engineering",
        "Design",
        "Product",
        "Data",
        "IT",
        "Marketing",
        "Sales",
        "Customer Support",
        "Operations",
        "Finance",
        "Human Resources",
        "Legal",
    ]:
        Category.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("jobs", "Category")
    Category.objects.filter(
        name__in=[
            "Engineering",
            "Design",
            "Product",
            "Data",
            "IT",
            "Marketing",
            "Sales",
            "Customer Support",
            "Operations",
            "Finance",
            "Human Resources",
            "Legal",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_category_job_benefits_job_deadline_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=unseed_categories),
    ]

