# Generated by Codex on 2026-04-21

from django.db import migrations


def backfill_job_fields(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")

    # Backfill salary_min/max from legacy `salary` where those fields are empty.
    for job in Job.objects.exclude(salary=None).filter(salary_min=None, salary_max=None):
        job.salary_min = job.salary
        job.salary_max = job.salary
        job.save(update_fields=["salary_min", "salary_max"])

    # Infer remote from location text for older rows.
    Job.objects.filter(is_remote=False, location__icontains="remote").update(is_remote=True)


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_seed_categories"),
    ]

    operations = [
        migrations.RunPython(backfill_job_fields, reverse_code=migrations.RunPython.noop),
    ]

