# Generated by Django 6.0.4 on 2026-04-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
