# Generated by Codex on 2026-04-21

from django.db import migrations
from django.utils import timezone


def lock_existing_roles(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(role_selected_at__isnull=True).update(role_selected_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_role_selected_at"),
    ]

    operations = [
        migrations.RunPython(lock_existing_roles, reverse_code=migrations.RunPython.noop),
    ]

